fn analyze_export_sources(sources: &[LoadedSource]) -> ExportSourceAnalysis {
    let mut analysis = ExportSourceAnalysis::default();
    for source in sources {
        let upper = source.text.to_ascii_uppercase();
        if upper.contains("VAR RETAIN") || upper.contains(" RETAIN ") || upper.contains("\nRETAIN")
        {
            analysis.has_retain_keyword = true;
        }
        if upper.contains("%I") || upper.contains("%Q") || upper.contains("%M") {
            analysis.has_direct_address_markers = true;
        }
        if upper.contains("SFB3") || upper.contains("SFB4") || upper.contains("SFB5") {
            analysis.has_siemens_aliases = true;
        }
        if upper.contains("TONR") {
            analysis.has_rockwell_aliases = true;
        }
        if upper.contains("R_EDGE") || upper.contains("F_EDGE") {
            analysis.has_schneider_aliases = true;
        }
    }
    analysis
}

fn adapter_report_path_for_output(output_path: &Path) -> PathBuf {
    let file_name = output_path
        .file_name()
        .and_then(|value| value.to_str())
        .unwrap_or("plcopen.xml");
    output_path.with_file_name(format!("{file_name}.adapter-report.json"))
}

fn siemens_scl_bundle_dir_for_output(output_path: &Path) -> PathBuf {
    let file_name = output_path
        .file_name()
        .and_then(|value| value.to_str())
        .unwrap_or("plcopen.siemens.xml");
    output_path.with_file_name(format!("{file_name}.scl"))
}

fn render_siemens_scl_types_file(types: &[DataTypeDecl]) -> String {
    let mut text = String::new();
    text.push_str("// Generated by trust-runtime plcopen export --target siemens\n");
    text.push_str("// Import in TIA Portal: External source files -> Add new external file\n\n");
    for data_type in types {
        text.push_str("TYPE\n");
        text.push_str(&format!(
            "    {} : {};\n",
            data_type.name.trim(),
            data_type.type_expr.trim()
        ));
        text.push_str("END_TYPE\n\n");
    }
    text
}

fn render_siemens_scl_pou(decl: &PouDecl) -> (String, Vec<String>) {
    let mut warnings = Vec::new();
    if !matches!(decl.pou_type, PlcopenPouType::Program) {
        return (decl.body.clone(), warnings);
    }

    let mut lines = decl
        .body
        .lines()
        .map(std::string::ToString::to_string)
        .collect::<Vec<_>>();
    let first_decl_idx = lines
        .iter()
        .position(|line| line.trim().to_ascii_uppercase().starts_with("PROGRAM "));
    let last_end_idx = lines
        .iter()
        .rposition(|line| line.trim().eq_ignore_ascii_case("END_PROGRAM"));

    match (first_decl_idx, last_end_idx) {
        (Some(start), Some(end)) if start < end => {
            lines[start] = format!("ORGANIZATION_BLOCK \"{}\"", decl.name);
            lines[end] = "END_ORGANIZATION_BLOCK".to_string();
            (lines.join("\n"), warnings)
        }
        _ => {
            warnings.push(format!(
                "{}:{} could not rewrite PROGRAM '{}' to Siemens ORGANIZATION_BLOCK form; exported IEC PROGRAM body as-is",
                decl.source, decl.line, decl.name
            ));
            (decl.body.clone(), warnings)
        }
    }
}

fn export_siemens_scl_bundle(
    output_path: &Path,
    declarations: &[PouDecl],
    data_types: &[DataTypeDecl],
    configurations: &[ConfigurationDecl],
    warnings: &mut Vec<String>,
) -> anyhow::Result<(PathBuf, Vec<PathBuf>)> {
    let bundle_dir = siemens_scl_bundle_dir_for_output(output_path);
    std::fs::create_dir_all(&bundle_dir).with_context(|| {
        format!(
            "failed to create Siemens SCL export directory '{}'",
            bundle_dir.display()
        )
    })?;

    let mut written = Vec::new();

    if !data_types.is_empty() {
        let types_path = bundle_dir.join("000_types.scl");
        let types_text = render_siemens_scl_types_file(data_types);
        std::fs::write(&types_path, types_text)
            .with_context(|| format!("failed to write '{}'", types_path.display()))?;
        written.push(types_path);
    }

    for (index, decl) in declarations.iter().enumerate() {
        let kind = match decl.pou_type {
            PlcopenPouType::Program => "ob",
            PlcopenPouType::Function => "fc",
            PlcopenPouType::FunctionBlock => "fb",
        };
        let file_name = format!(
            "{:03}_{}_{}.scl",
            index + 1,
            kind,
            sanitize_filename(&decl.name)
        );
        let path = bundle_dir.join(file_name);
        let (body, mut body_warnings) = render_siemens_scl_pou(decl);
        warnings.append(&mut body_warnings);

        let mut file_text = String::new();
        file_text.push_str("// Generated by trust-runtime plcopen export --target siemens\n");
        file_text.push_str(&format!("// Source: {}:{}\n\n", decl.source, decl.line));
        file_text.push_str(&body);
        if !body.ends_with('\n') {
            file_text.push('\n');
        }

        std::fs::write(&path, file_text)
            .with_context(|| format!("failed to write '{}'", path.display()))?;
        written.push(path);
    }

    if !configurations.is_empty() {
        let notes_path = bundle_dir.join("900_tia_mapping_notes.txt");
        let mut notes = String::new();
        notes.push_str("Generated by trust-runtime plcopen export --target siemens\n");
        notes.push_str("CONFIGURATION/RESOURCE/TASK/PROGRAM wiring requires manual OB/task mapping in TIA Portal.\n");
        notes.push_str("Use interop/*.adapter-report.json for detailed migration diagnostics and manual steps.\n");
        std::fs::write(&notes_path, notes)
            .with_context(|| format!("failed to write '{}'", notes_path.display()))?;
    }

    Ok((bundle_dir, written))
}

fn export_adapter_diagnostic(
    code: &str,
    severity: &str,
    message: impl Into<String>,
    action: impl Into<String>,
) -> PlcopenExportAdapterDiagnostic {
    PlcopenExportAdapterDiagnostic {
        code: code.to_string(),
        severity: severity.to_string(),
        message: message.into(),
        action: action.into(),
    }
}

fn build_export_adapter_contract(
    target: PlcopenExportTarget,
    context: &ExportTargetValidationContext,
) -> Option<PlcopenExportAdapterContract> {
    let mut diagnostics = Vec::new();
    let has_project_model = context.configuration_count > 0
        || context.resource_count > 0
        || context.task_count > 0
        || context.program_instance_count > 0;

    let (manual_steps, limitations) = match target {
        PlcopenExportTarget::Generic => return None,
        PlcopenExportTarget::AllenBradley => {
            diagnostics.push(export_adapter_diagnostic(
                "PLCO7AB0",
                "info",
                format!(
                    "Generated AB adapter artifact from {} source file(s) and {} ST declaration(s).",
                    context.source_count,
                    context.pou_count + context.data_type_count
                ),
                "Use the adapter report as the import checklist for Studio 5000 migration.",
            ));
            if has_project_model {
                diagnostics.push(export_adapter_diagnostic(
                    "PLCO7AB1",
                    "warning",
                    "Configuration/resource/task/program bindings require manual task mapping in Studio 5000.",
                    "Recreate periodic/continuous task wiring and bind imported program routines manually.",
                ));
            }
            if context.analysis.has_direct_address_markers {
                diagnostics.push(export_adapter_diagnostic(
                    "PLCO7AB2",
                    "warning",
                    "Detected direct `%I/%Q/%M` addressing markers.",
                    "Map tags to controller I/O aliases manually and verify address classes before deployment.",
                ));
            }
            if context.analysis.has_retain_keyword {
                diagnostics.push(export_adapter_diagnostic(
                    "PLCO7AB3",
                    "warning",
                    "Detected RETAIN usage that may not map 1:1 to Logix persistence semantics.",
                    "Review controller-scoped retentive tags and startup/reset behavior in commissioning tests.",
                ));
            }
            if context.analysis.has_siemens_aliases || context.analysis.has_schneider_aliases {
                diagnostics.push(export_adapter_diagnostic(
                    "PLCO7AB4",
                    "warning",
                    "Detected non-AB vendor alias symbols in ST sources.",
                    "Normalize vendor-specific aliases to IEC/AB-native symbols before final import.",
                ));
            }

            (
                vec![
                    "Import the generated PLCopen XML via your AB migration flow (converter/toolchain of choice).".to_string(),
                    "Recreate task classes and scan rates in Studio 5000, then bind each program routine.".to_string(),
                    "Rebind `%I/%Q/%M` markers to controller tags and physical I/O aliases.".to_string(),
                    "Run conformance and project acceptance tests after migration.".to_string(),
                ],
                vec![
                    "v1 generates PLCopen XML + adapter diagnostics, not native .L5X output.".to_string(),
                    "AOI internals, safety signatures, and controller module metadata are not generated.".to_string(),
                    "Retentive/runtime startup semantics require manual validation on target hardware.".to_string(),
                ],
            )
        }
        PlcopenExportTarget::Siemens => {
            diagnostics.push(export_adapter_diagnostic(
                "PLCO7SI0",
                "info",
                format!(
                    "Generated Siemens adapter artifact from {} source file(s) and {} ST declaration(s).",
                    context.source_count,
                    context.pou_count + context.data_type_count
                ),
                "Use the adapter report as the import checklist for TIA Portal migration.",
            ));
            if has_project_model {
                diagnostics.push(export_adapter_diagnostic(
                    "PLCO7SI1",
                    "warning",
                    "Configuration/resource/task/program bindings require manual OB/task mapping in TIA Portal.",
                    "Map PLCopen tasks to cyclic/event OBs and bind program instances explicitly.",
                ));
            }
            if context.analysis.has_direct_address_markers {
                diagnostics.push(export_adapter_diagnostic(
                    "PLCO7SI2",
                    "warning",
                    "Detected direct `%I/%Q/%M` addressing markers.",
                    "Reconcile address markers with TIA memory areas and hardware configuration manually.",
                ));
            }
            if context.analysis.has_rockwell_aliases {
                diagnostics.push(export_adapter_diagnostic(
                    "PLCO7SI3",
                    "warning",
                    "Detected Rockwell-specific library aliases in ST sources.",
                    "Replace Rockwell aliases/functions with IEC or Siemens-native equivalents before import.",
                ));
            }

            (
                vec![
                    "Import generated `.scl` files from the Siemens SCL sidecar bundle via TIA Portal: External source files -> Add new external file.".to_string(),
                    "Generate blocks from each imported source file in TIA Portal.".to_string(),
                    "Map tasks/program instances to OB scheduling and call hierarchy in TIA Portal.".to_string(),
                    "Validate memory-marker and retentive data behavior against PLC commissioning tests.".to_string(),
                    "Run conformance plus project-specific smoke tests after migration.".to_string(),
                ],
                vec![
                    "v1 generates PLCopen XML + `.scl` source bundle + adapter diagnostics, not native .apXX project archives.".to_string(),
                    "Hardware topology, technology objects, and safety project metadata are not generated.".to_string(),
                    "Vendor library semantics beyond symbol-level mapping remain manual migration work.".to_string(),
                ],
            )
        }
        PlcopenExportTarget::Schneider => {
            diagnostics.push(export_adapter_diagnostic(
                "PLCO7SC0",
                "info",
                format!(
                    "Generated Schneider adapter artifact from {} source file(s) and {} ST declaration(s).",
                    context.source_count,
                    context.pou_count + context.data_type_count
                ),
                "Use the adapter report as the import checklist for EcoStruxure migration.",
            ));
            if has_project_model {
                diagnostics.push(export_adapter_diagnostic(
                    "PLCO7SC1",
                    "warning",
                    "Configuration/resource/task/program bindings require manual task scheduling setup in EcoStruxure.",
                    "Rebuild task classes and program assignment explicitly after import.",
                ));
            }
            if context.analysis.has_direct_address_markers {
                diagnostics.push(export_adapter_diagnostic(
                    "PLCO7SC2",
                    "warning",
                    "Detected direct `%I/%Q/%M` addressing markers.",
                    "Rebind addressing to controller I/O map and validate with target hardware mapping rules.",
                ));
            }
            if context.analysis.has_siemens_aliases || context.analysis.has_rockwell_aliases {
                diagnostics.push(export_adapter_diagnostic(
                    "PLCO7SC3",
                    "warning",
                    "Detected non-Schneider vendor aliases in ST sources.",
                    "Normalize aliases to IEC/Schneider-supported equivalents before import.",
                ));
            }
            if context.analysis.has_retain_keyword {
                diagnostics.push(export_adapter_diagnostic(
                    "PLCO7SC4",
                    "warning",
                    "Detected RETAIN usage that may need explicit persistence configuration.",
                    "Verify retained variable classes and persistence files in EcoStruxure runtime settings.",
                ));
            }

            (
                vec![
                    "Import the generated PLCopen XML via the Schneider/CODESYS interchange path.".to_string(),
                    "Recreate task scheduling and program assignment in EcoStruxure project settings.".to_string(),
                    "Rebind hardware addresses and persistence settings before deployment.".to_string(),
                    "Run conformance and project integration tests after migration.".to_string(),
                ],
                vec![
                    "v1 generates PLCopen XML + adapter diagnostics, not native EcoStruxure project archives.".to_string(),
                    "Device-tree, bus topology, and safety metadata are not generated.".to_string(),
                    "Vendor-specific library internals remain manual migration work beyond symbol-level adaptation.".to_string(),
                ],
            )
        }
    };

    Some(PlcopenExportAdapterContract {
        diagnostics,
        manual_steps,
        limitations,
    })
}

