version = 1

[theme]
style = "industrial"
accent = "#c2410c"

[layout]
navigation = "sidebar-left"
header = true
header_title = "Main HMI"

[write]
enabled = false
allow = []

[[alarm]]
bind = "Main.CycleSeconds"
high = 100
low = 0
deadband = 2
inferred = true
label = "Cycle Seconds"

[[alarm]]
bind = "Main.RunHours"
high = 100
low = 0
deadband = 2
inferred = true
label = "RUN Hours"
